server:
  port: 5000
spring:
  application:
    name: tms‐service‐manage
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017
#      database: xc_cms
  freemarker:
    cache: false #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0
#  rabbitmq:
#    host: 192.168.142.128
#    port: 5672
#    username: guest
#    password: guest
#    virtualHost: /